#!/bin/bash

set -e
if git diff-index --quiet HEAD; then
	exit 0
fi
git config --global user.email "actions@github.com"
git config --global user.name "Github Actions"

git pull
git checkout "$GITHUB_REF"
git add .
git commit --amend --no-edit
git push
