name: CI

on: [push]

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - name: prettier
        uses: m59peacemaker/actions/prettier@master
        env:
          GITHUB_TOKEN: ''
        with:
          args: 'autofix'
