name: CI

on: [push]

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: prettier
        run: npx prettier --write '*.js'
      - name: commit
        run: ./scripts/commit
