name: CI

on: [push]

jobs:
  lint-fix:
    runs-on: node-12-alpine
    steps:
    - name: prettier
      uses: bltavares/actions/prettier@master
      #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
      with:
        args: 'autofix'
