name: CI

on: [push]

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: prettier
        run: npx prettier --write '*.js'
      - name: commit
        run:  |
          set -e \
          if git diff-index --quiet HEAD; then
            exit 0
          fi
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git add .
          git commit --amend --no-edit
          git push
